name: reuse other one
on: {workflow_dispatch}
        

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      greetee: Me
      
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Said hi at ${{ needs.call-workflow.outputs.current-time }}"
