name: reuse other one
on: 
  workflow_dispatch:
    inputs:
      name:
        description: Who do you want to say hi to?
        type: string
        default: world

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      greetee: ${{ inputs.name }}
      
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Said hi to ${{ needs.call-workflow.outputs.greetee }} at ${{ needs.call-workflow.outputs.current-time }}"
