name: reuseable workflow

on:
  workflow_call:
    inputs:
      greetee:
        type: string
        required: true
        default: World
        description: Who do you want to say hi to?
        
    outputs:
      current-time:
        value: ${{ jobs.reusable.job.outputs.current-time}}
      
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greeter
        run: echo "Hello ${{ inputs.greetee}}"
      - name: set time  
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

